# Generated by Django 3.2.4 on 2021-06-19 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('msg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('content_type', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('msg_status', models.TextField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups')),
                ('rx_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rx_id', to='user.user')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='user.user')),
            ],
        ),
    ]
